Upgrade PGML and pgVector (#77)
tembo-io/tembo-images pull request #77
Opened 2024-12-21 00:43 UTC by theory

Also remove the unused `PGEMBEDDING_VERSION` argument.

2024-12-21 00:46 UTC, ChuckHend reviewed
This will need to be built and then tested in dev before its released. The last I tried (which is a long time ago now), I was not able to get xgboost to function properly (via pgml in postgres) in our cloud for any pgml version > 2.7.1.

2024-12-21 00:52 UTC, ChuckHend requested changes
The dockerfile will need to be updated to install pgml and its dependencies from source.

Then, test that the extension can not only be loaded but also that it functions properly. e.g. train a classification model, then load it and run some .predict through it. You could use the example in the [ML Stack Docs](https://tembo.io/docs/product/stacks/ai/machine-learning) as way to test it. If you can get through the guide, then its probably good enough.

2024-12-21 00:52 UTC, theory commented
New years goals.

2024-12-21 00:54 UTC, nhudson approved these changes

2024-12-21 00:59 UTC, ChuckHend commented
For when we come back to this https://github.com/postgresml/postgresml/blob/master/docker/Dockerfile

2025-01-03 00:38 UTC, nhudson approved these changes

2025-01-17 16:14 UTC, ChuckHend approved these changes

2025-01-17 18:34 UTC, merged